### PR TITLE
core: ping: limit maximum baudrate of ping1d to 115200 for now.

### PR DESCRIPTION
**Pull request by Williangalvani**
Pin1D is having issues running at higher bauds, this limits it to 115200 for now.

### CODE REVIEW

**Comment by patrickelectric** [comment]
@Williangalvani will this PR fix the problem that I tried to replicate today ? 
Can you point what is this fixing ? 
My ping1D plus ping-viewer worked fine at 4M

**Comment by Williangalvani** [comment]
> @Williangalvani will this PR fix the problem that I tried to replicate today ?
> Can you point what is this fixing ?
> My ping1D plus ping-viewer worked fine at 4M

that is odd. mine and Brian's don't.
let's wait for his feedback. I asked him to test this, too.

**Comment by patrickelectric** [comment]
I'll try again tomorrow and see how it goes one more time, maybe it was luck

**Comment by Williangalvani** [comment]
to be clearer:
it may work from time to time, but it stutters a lot, apparently loosing a lot of packets, and the final result is worse than 115200.

**Comment by patrickelectric** [comment]
Oh, I'll test again.
I just want to make sure that we find the problem and fix in the right place, without knowing the source of such problem, we may be "hiding" the original source of the problem fixing the baudrate to a specific number. And probably in the near future a problem closer or related to the source of this one may be a future pain for us.

**Comment by patrickelectric** [comment]
Closing in favor of #329

**Pull request closed without merging**
