### PR TITLE
Update for navigator R3 support

### PR DESCRIPTION
**Pull request by jaxxzer**

### CODE REVIEW

**Comment by jaxxzer** [comment]
@patrickelectric sorry for any issue.

1. I did make the PR against my own fork
2. I made the branch on this repository because I wanted an image on docker hub, and I thought that was the way
3. When I was looking last night, the 'master' image on docker hub was replaced when this (jaxxzer/r3) PR CI finished, I don't know if that's expected.
4. I was unable to test the install using `export VERSION` and `export REMOTE`, because the boards step is always downloaded from BR master.

**Comment by jaxxzer** [comment]
I tried
```
export VERSION=r3
export REMOTE=https://github.com/jaxxzer/companion-docker
sudo su -c 'curl -fsSL https://raw.githubusercontent.com/jaxxzer/companion-docker/r3/install/install.sh | bash'
```

The changes to bcm27xx would not run.
can you try it @patrickelectric ?

**Comment by patrickelectric** [comment]
Thanks, I'll investigate it: https://github.com/bluerobotics/companion-docker/issues/123
The docker deploy script will push any branch as master, I'll also fix that: https://github.com/bluerobotics/companion-docker/issues/124

**Comment by patrickelectric** [comment]
> I tried
> 
> ```
> export VERSION=r3
> export REMOTE=https://github.com/jaxxzer/companion-docker
> sudo su -c 'curl -fsSL https://raw.githubusercontent.com/jaxxzer/companion-docker/r3/install/install.sh | bash'
> ```
> 
> The changes to bcm27xx would not run.
> can you try it @patrickelectric ?

This instructions are wrong, `sudo su` will not have access to variables of `pi`, you should do:
- `sudo su`
- Set environment variables
- Call: `curl -fsSL https://raw.githubusercontent.com/jaxxzer/companion-docker/r3/install/install.sh | bash`


To test the docker, you can just push it to your own dockerhub and change bootstrap settings to use your version.

**Review by rafaellehmkuhl — APPROVED** [review]

**Review by patrickelectric — APPROVED** [review]
The patch looks great, the only thing missing the prefix:
`install:`  for the first 4 commits and `core:` to the latest commit, with that we can easily find looking in the history when a change occurs in one of the specific modules, such as: `install`, `core` and `bootstrap`

**Pull request merged**
