### PR TITLE
Add linux2rest, a rest API + interface for system information 

### PR DESCRIPTION
**Pull request by patrickelectric**
Available under port 6030
To test: it's necessary to add the following bind in the bootstrap config:
```
"/sys/": {
    "bind": "/sys/",
    "mode": "r"
},
```
And use the following image:
`patrickelectric/companion-core:linux2rest`

### CODE REVIEW

**Review by rafaellehmkuhl — APPROVED** [review]

**Comment by Williangalvani** [comment]
This looked weird for me both in Linux and Windows:

https://user-images.githubusercontent.com/4013804/115614457-1d12e780-a2c4-11eb-8e01-0b36842b1ade.mp4

photo5767062586926413221

Maybe try a different icon?

**Comment by patrickelectric** [comment]
@Williangalvani fixed in the last version

**Comment by Williangalvani** [comment]
so.... I have a different symbol now...

https://user-images.githubusercontent.com/4013804/115766664-98d16a80-a37e-11eb-9c67-528af178c7d9.mp4

**Comment by patrickelectric** [comment]
> so.... I have a different symbol now...
> 
>  wat3.mp4

Try under android, mac and windows
It works for me, check your installed fonts.

**Comment by patrickelectric** [comment]
@Williangalvani the latest version changes the HTML charset to utf-8 as default, this should fix any problem related to systems that are not configured to utf-8.

**Review by Williangalvani — APPROVED** [review]
lgtm

**Pull request merged**
