### PR TITLE
core: ardupilot-manager: Make default GCS endpoint an UDP server

### PR DESCRIPTION
**Pull request by rafaellehmkuhl**
First step to solve #418 

Image available at `rafaellehmkuhl/companion-core:gcs-endpoint`

### CODE REVIEW

**Review by patrickelectric — APPROVED** [review]
I believe that this is the correct approach.

**Comment by Williangalvani** [comment]
I really, really dislike needing to set up the connection manually in QGC.

**Comment by patrickelectric** [comment]
> I really, really dislike needing to set up the connection manually in QGC.

Can we make it temporary until we sort the companion GCS integration ?
The idea is to make QGC find companion in the network.

**Comment by rafaellehmkuhl** [comment]
I've added to this discussion on #418 @Williangalvani

**Review by Williangalvani — APPROVED** [review]
sounds good for now. we should add a note in the frontend to notify users they need to add a new connection in QGC

**Comment by patrickelectric** [comment]
Maybe a popup ?

**Review by patrickelectric — APPROVED** [review]

**Comment by rafaellehmkuhl** [comment]
New alert:

image

**Pull request merged**
