### PR TITLE
.eslint: remove ForOFStatement restriction

### PR DESCRIPTION
**Pull request by Williangalvani**
We believe ForOf statements are more readable, and readability comes first. Let the developer decide which one to use at its own discretion.

### CODE REVIEW

**Comment by patrickelectric** [comment]
My point is that forEach function can be replaced with the map function.

**Review by patrickelectric — APPROVED** [review]

**Review by rafaellehmkuhl — APPROVED** [review]

**Comment by rafaellehmkuhl** [comment]
> My point is that forEach function can be replaced with the map function.

We should not use map functions to apply side-effects, though. Eslint will block, also.

**Comment by patrickelectric** [comment]
> > My point is that forEach function can be replaced with the map function.
> 
> We should not use map functions to apply side-effects, though. Eslint will block, also.

which side-effects ? map functions are much clear than raw for loops

**Comment by rafaellehmkuhl** [comment]
> > > My point is that forEach function can be replaced with the map function.
> > 
> > 
> > We should not use map functions to apply side-effects, though. Eslint will block, also.
> 
> which side-effects ? map function are much clear than raw for loops

`map` is functional. It should just take an original array and map it into another, without side-effects.

When you want to cause side-effects you should use a forEach or for loop.

**Comment by patrickelectric** [comment]
> `map` is functional. It should just take an original array and map it into another, without side-effects.
> 
> When you want to cause side-effects you should use a forEach or for loop.

Ok, I understand what you want to said now, thanks!

**Pull request merged**
