### PR TITLE
core: tools: mavlink_camera_manager: Update to version t3.0.11

### LINKED ISSUE #494: Video manager: use "inactive" flag to deactivate controls in the frontend.
Related to https://github.com/patrickelectric/mavlink-camera-manager/issues/10

### LINKED ISSUE #649: video_manager: Do not report video as rtsp when running as h264

### PR DESCRIPTION
**Pull request by patrickelectric**
- Provide correct video type over mavlink, RTPUDP over RTSP
- Add stats in V4L control to inform if it's disabled or inactive

Fix #649
Fix #494 

Available on: patrickelectric/companion-core:update_camera_manager

### CODE REVIEW

**Comment by rafaellehmkuhl** [comment]
Couldnt find an image available to test the PR.

**Comment by patrickelectric** [comment]
> Couldnt find an image available to test the PR.

You can download from github actions :eyes: 
This only updates the video stream mavlink message from the camera manager

**Comment by patrickelectric** [comment]
But I can create a new one later today

**Comment by rafaellehmkuhl** [comment]
> > Couldnt find an image available to test the PR.
> 
> You can download from github actions 👀 This only updates the video stream mavlink message from the camera manager

Yeaaaah
Without sideload this is still a little cumbersome haha


> This only updates the video stream mavlink message from the camera manager

My only concern is if the frontend will behave correctly without the missing new options, but I think it will

**Comment by rafaellehmkuhl** [comment]
> > Couldnt find an image available to test the PR.
> 
> You can download from github actions 👀 This only updates the video stream mavlink message from the camera manager

Once you download the file, what are the commands you're using?

**Comment by patrickelectric** [comment]
> > > Couldnt find an image available to test the PR.
> > 
> > 
> > You can download from github actions eyes This only updates the video stream mavlink message from the camera manager
> 
> Once you download the file, what are the commands you're using?

https://docs.docker.com/engine/reference/commandline/load/

**Review by rafaellehmkuhl — APPROVED** [review]

**Pull request merged**
