### PR TITLE
Rename deploy action to "Build and Depĺoy Images"

### PR DESCRIPTION
**Pull request by Williangalvani**
I'm always asking myself why a "deploy" action is running on a Pull Request.

(Yes, I used the github web interface to open this PR and I'm not ashamed)

### CODE REVIEW

**Review by rafaellehmkuhl — CHANGES_REQUESTED** [review]
Would just put a `CI: ...` before the commit message to follow our currently pattern.

**Comment by rafaellehmkuhl** [comment]
> I'm always asking myself why a "deploy" action is running on a Pull Request.
> 
> (Yes, I used the github web interface to open this PR and I'm not ashamed)

For small things it's NEAT

**Comment by patrickelectric** [comment]
> (Yes, I used the github web interface to open this PR and I'm not ashamed)

And since you did that, you have crated a branch, and because of that, now there is a new tag on dockerhub..
image

**Comment by Williangalvani** [comment]
> And since you did that, you have crated a branch, and because of that, now there is a new tag on dockerhub..

I remember thinking "damn, it doesn't let me create a branch on my fork. Well, what could go wrong?"

Now I know the answer!

Anyway, fixed the commit msg

**Review by patrickelectric — APPROVED** [review]

**Pull request merged**
