### PR TITLE
core: Add docker REST API access 

### PR DESCRIPTION
**Pull request by patrickelectric**
Only allow get methods

### CODE REVIEW

**Comment by rafaellehmkuhl** [comment]
Cool! Do you have an image for test?

**Comment by patrickelectric** [comment]
Available in: patrickelectric/companion-core:docker-api

**Comment by patrickelectric** [comment]
Not working, going to fix it soon

**Comment by patrickelectric** [comment]
as a reminder, unix socket files are not files :eyes: 
It's necessary to check with `-e` and not `-f`.

If someone wants to try now: http://companion.local/docker/v1.41/info

**Comment by rafaellehmkuhl** [comment]
Working beautifully. Great!

**Review by rafaellehmkuhl — APPROVED** [review]

**Pull request merged**
