### PR TITLE
Bootstrap: Fix config file path

### PR DESCRIPTION
**Pull request by Williangalvani**
It was erroneously trying to mount the startup.json file as a volume instead of the parent directory it is in. You cannot mount a file as a volume.

This makes docker mount the correct volume in line 57

for testing, use williangalvani/bootstrap:master in install.sh

### CODE REVIEW

**Review by jaxxzer — APPROVED** [review]

**Comment by Williangalvani** [comment]
I can't figure out what is going on with CI here...

**Comment by patrickelectric** [comment]
@Williangalvani can you disable fakefs ? it appears to be stuck on that part

**Comment by patrickelectric** [comment]
It really looks that one of the tests are just stuck, my PR did pass by CI without problems here: https://github.com/bluerobotics/companion-docker/pull/64

**Comment by Williangalvani** [comment]
> It really looks that one of the tests are just stuck

You were right. Updated testes and added timeouts.

**Comment by patrickelectric** [comment]
@Williangalvani is the latest version available in dockerhub ?

**Comment by patrickelectric** [comment]
@Williangalvani tests are failing

**Review by patrickelectric — APPROVED** [review]

**Pull request merged**
