### PR TITLE
core: linux2rest: Update version with relative URL calls

### PR DESCRIPTION
**Pull request by patrickelectric**
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by patrickelectric** [comment]
docker: patrickelectric/companion-core:linux2rest_relative

**Review by rafaellehmkuhl — APPROVED** [review]
All network calls seem to be working fine.

There is a bug though, that doesn't seem to be connected to this PR, that prevents kernel messages to appear:

image

image

**Comment by rafaellehmkuhl** [comment]
Updating:

Updates on kernel work using service port (`:6030`) but not using path (`/system-information`).

image

image

Both results above were performed reconnecting a usb drive.

**Comment by patrickelectric** [comment]
@rafaellehmkuhl this is a nginx problem where the websocket configuration does not exist for this service, check:
https://github.com/bluerobotics/companion-docker/pull/372

**Review by rafaellehmkuhl — APPROVED** [review]
Approving together with #372 (which solves the websocket problems from last review).

**Pull request merged**
