### PR TITLE
core: tools: mavlink_camera_manager: Update to version t3.1.1

### PR DESCRIPTION
**Pull request by patrickelectric**
docker image (updated to 3.1.1): `patrickelectric/companion-core:update_mavlink_camera_manager_3_1_0`

[changelog](https://github.com/bluerobotics/mavlink-camera-manager/releases/tag/t3.1.1)

### CODE REVIEW

**Review by rafaellehmkuhl — APPROVED** [review]
It's already working, so approving.
I will send a small patch to fix the UsbBusType to string, to make the types correct (we were not using this info yet, so it didn't break anything).

**Comment by Williangalvani** [comment]
So.... This is creating streams at 15fps as a default...

image

**Comment by patrickelectric** [comment]
@joaoantoniocardoso ^

**Comment by joaoantoniocardoso** [comment]
Yeah, I noticed that too, but I didn't thought we were using the order in that way. Essentially, the technique we used to prevent duplicates is reordering the sizes vectors (from lower to higher value). As it seems, we are getting the first value from that vector as the default, is that right?

If so, we can simply invert the ordering on the mavlink-camera-manager side.

**Comment by rafaellehmkuhl** [comment]
Strange thing is that, for the ball fake source, the order is correct.

> Yeah, I noticed that too, but I didn't thought we were using the order in that way. Essentially, the technique we used to prevent duplicates is reordering the sizes vectors (from lower to higher value). As it seems, we are getting the first value from that vector as the default, is that right?
> 
> If so, we can simply invert the ordering on the mavlink-camera-manager side.

**Comment by joaoantoniocardoso** [comment]
@rafaellehmkuhl  I think `fakes` aren't set by the same means as the local devices.

This should fix it: https://github.com/bluerobotics/mavlink-camera-manager/pull/25

**Comment by patrickelectric** [comment]
The new version t3.1.1 has a fix, I'm going to update the PR asap.

**Review by rafaellehmkuhl — APPROVED** [review]

**Pull request merged**
