### PR TITLE
core: mavlink-camera-manager: Update version with relative URL calls

### PR DESCRIPTION
**Pull request by patrickelectric**
Fix problem relative to URL redirect with HTTP server

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by patrickelectric** [comment]
The error is in nginx install, PR #348 aims to fix that.

**Comment by Williangalvani** [comment]
I found an issue:
image

I believe it can be fixed by replacing `URL('delete_stream')` for `URL('delete_stream', window.location)` at https://github.com/patrickelectric/mavlink-camera-manager/blob/master/src/html/index.html#L115

**Comment by Williangalvani** [comment]
> The error is in nginx install, PR #348 aims to fix that.

Weird. I managed to build the image locally. maybe it is just some instability on their servers.

**Comment by patrickelectric** [comment]
> Weird. I managed to build the image locally. maybe it is just some instability on their servers.

I got this problem several times already in others PRs, but just to be safe, I believe that is a good approach to have update before install.

**Comment by patrickelectric** [comment]
@Williangalvani check docker: camera_manager_relative

**Review by Williangalvani — APPROVED** [review]

**Pull request merged**
