### PR TITLE
core: tool: mavlink_camera_manager: Update to t3.0.4

### PR DESCRIPTION
**Pull request by patrickelectric**
Fix pipeline reset with Blue Robotics low light camera

Docker: patrickelectric/companion-core:mavlink-camera-manager-t3.0.4

### CODE REVIEW

**Review by rafaellehmkuhl — APPROVED** [review]

**Comment by patrickelectric** [comment]
Dont you have it ?
https://bluerobotics.com/store/sensors-sonars-cameras/cameras/cam-usb-low-light-r1/

**Comment by rafaellehmkuhl** [comment]
Ow, I thought my camera as a "regular" one. Didn't know all our cameras were low-light kk

**Comment by patrickelectric** [comment]
The regular camera for the ROV is the low light camera

**Review by Williangalvani — APPROVED** [review]
Working nicely here.

**Pull request merged**
